# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-15 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice_1', '0002_author_book_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='practice_1.User'),
            preserve_default=False,
        ),
    ]
